// C
export const ADD_CHARACTER = "ADD_CHARACTER";
export const ADD_CHARACTER_DONE = "ADD_CHARACTER_DONE";
export const ADD_CHARACTER_ERROR = "ADD_CHARACTER_ERROR";

// R
export const WIEW_CHARACTERS = "WIEW_CHARACTERS";
export const WIEW_CHARACTERS_DONE = "WIEW_CHARACTERS_DONE";
export const WIEW_CHARACTERS_ERROR = "WIEW_CHARACTERS_ERROR";

// U
export const UPDATE_CHARACTER = "UPDATE_CHARACTER";
export const UPDATE_CHARACTER_EDIT = "UPDATE_CHARACTER_EDIT";
export const UPDATE_CHARACTER_DONE = "UPDATE_CHARACTER_DONE";
export const UPDATE_CHARACTER_ERROR = "UPDATE_CHARACTER_ERROR";

// D
export const DEL_CHARACTER = "DEL_CHARACTER";
export const DEL_CHARACTER_DONE = "DEL_CHARACTER_DONE";
export const DEL_CHARACTER_ERROR = "DEL_CHARACTER_ERROR";
